ResumeBuilder.Web/Areas/Admin/Controllers/AdminController.cs
using System.Web.Mvc;
using ResumeBuilder.Domain.Constants;
using ResumeBuilder.Domain.Interfaces.Services;
using ResumeBuilder.Domain.Interfaces.UnitOfWork;
using System.Text;
using System.Collections.Specialized;
using System.IO;

namespace ResumeBuilder.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = AppConstants.RoleNameSuperAdmin)]
    public class AdminController : BaseAdminController
    {

        public AdminController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, IMembershipService membershipService, ISettingsService settingsService)
            : base(loggingService, unitOfWorkManager, membershipService, settingsService)
        {
        }

        /// <summary>
        /// Default page for the admin area
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

    }
}

ResumeBuilder.Web/Areas/Admin/Controllers/LogController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using ResumeBuilder.Domain.Constants;
using ResumeBuilder.Domain.DomainModel;
using ResumeBuilder.Domain.Interfaces.Services;
using ResumeBuilder.Domain.Interfaces.UnitOfWork;
using ResumeBuilder.ViewModels.Admin;
using ResumeBuilder.ViewModels;

namespace ResumeBuilder.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = AppConstants.RoleNameSuperAdmin)]
    public class LogController : BaseAdminController
    {
        public LogController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, IMembershipService membershipService, ISettingsService settingsService) :
            base(loggingService, unitOfWorkManager, membershipService, settingsService)
        {

        }

        public ActionResult Index()
        {
            IList<LogEntry> logs = new List<LogEntry>();

            try
            {
                logs = LoggingService.ListLogFile();
            }
            catch (Exception ex)
            {
                var err = string.Format("Unable to access logs: {0}", ex.Message);
                TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                {
                    Message = err,
                    MessageType = GenericMessages.error
                };

                LoggingService.Error(err);
            }

            return View(new ListLogViewModel { LogFiles = logs });
        }

        public ActionResult ClearLog()
        {
            LoggingService.ClearLogFiles();

            TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
            {
                Message = "Log File Cleared",
                MessageType = GenericMessages.success
            };
            return RedirectToAction("Index");
        }

    }
}

ResumeBuilder.Web/Areas/Admin/Controllers/SettingsController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using ResumeBuilder.Domain.Constants;
using ResumeBuilder.Domain.DomainModel;
using ResumeBuilder.Domain.Interfaces.Services;
using ResumeBuilder.Domain.Interfaces.UnitOfWork;
using ResumeBuilder.Utilities;
using ResumeBuilder.Web.Application;
using ResumeBuilder.ViewModels.Admin;
using ResumeBuilder.ViewModels.Mapping;
using ResumeBuilder.ViewModels;

namespace ResumeBuilder.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = AppConstants.RoleNameSuperAdmin)]
    public class SettingsController : BaseAdminController
    {
        private readonly IRoleService _roleService;
        private readonly IEmailService _emailService;

        public SettingsController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager,
            IMembershipService membershipService,
            IRoleService roleService,
            ISettingsService settingsService, IEmailService emailService)
            : base(loggingService, unitOfWorkManager, membershipService, settingsService)
        {
            _roleService = roleService;
            _emailService = emailService;
        }

        public ActionResult Index()
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var currentSettings = SettingsService.GetSettings();
                var settingViewModel = ViewModelMapping.SettingsToSettingsViewModel(currentSettings);
                settingViewModel.NewMemberStartingRole = _roleService.GetRole(SettingsService.GetSettings().NewMemberStartingRole.Id).Id;
                settingViewModel.Roles = _roleService.AllRoles().ToList();
                return View(settingViewModel);
            }
        }

        [HttpPost]
        public ActionResult Index(EditSettingsViewModel settingsViewModel)
        {
            if (ModelState.IsValid)
            {
                using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
                {
                    try
                    {

                        var existingSettings = SettingsService.GetSettings();
                        var updatedSettings = ViewModelMapping.SettingsViewModelToSettings(settingsViewModel, existingSettings);

                        // Map over viewModel from 
                        if (settingsViewModel.NewMemberStartingRole != null)
                        {
                            updatedSettings.NewMemberStartingRole =
                                _roleService.GetRole(settingsViewModel.NewMemberStartingRole.Value);
                        }

                        unitOfWork.Commit();

                        // Set the culture session too
                        //Session["Culture"] = culture;
                    }
                    catch (Exception ex)
                    {
                        unitOfWork.Rollback();
                        LoggingService.Error(ex);
                    }
                }

                // All good clear cache and get reliant lists
                using (UnitOfWorkManager.NewUnitOfWork())
                {
                    TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                    {
                        Message = "Settings Updated",
                        MessageType = GenericMessages.success
                    };
                    settingsViewModel.Roles = _roleService.AllRoles().ToList();
                }
            }
            return View(settingsViewModel);
        }

        public ActionResult TestEmail()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SendTestEmail()
        {
            var sb = new StringBuilder();
            sb.AppendFormat("<p>{0}</p>", string.Concat("This is a test email from ", SettingsService.GetSettings().ApplicationName));
            var email = new Email
            {
                EmailFrom = SettingsService.GetSettings().AdminEmailAddress,
                EmailTo = SettingsService.GetSettings().AdminEmailAddress,
                NameTo = "Email Test Admin",
                Subject = string.Concat("Email Test From ", SettingsService.GetSettings().ApplicationName)
            };
            email.Body = _emailService.EmailTemplate(email.NameTo, sb.ToString());
            _emailService.SendMail(email);

            TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
            {
                Message = "Test Email Sent",
                MessageType = GenericMessages.success
            };
            return RedirectToAction("TestEmail");
        }
    }
}

ResumeBuilder.Web/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Principal;
using System.Text;
using System.Web.Mvc;
using System.Web.Security;
using ResumeBuilder.Domain.Constants;
using ResumeBuilder.Domain.DomainModel;
using ResumeBuilder.Domain.Interfaces.Services;
using ResumeBuilder.Domain.Interfaces.UnitOfWork;
using ResumeBuilder.Utilities;
using ResumeBuilder.ViewModels;
using MembershipCreateStatus = ResumeBuilder.Domain.DomainModel.MembershipCreateStatus;
using MembershipUser = ResumeBuilder.Domain.DomainModel.MembershipUser;
using ResumeBuilder.Web.Application;

namespace ResumeBuilder.Web.Controllers
{
    public class MembersController : BaseController
    {
        private readonly IEmailService _emailService;

        //private MembershipUser LoggedOnUser;
        //private MembershipRole UsersRole;

        //private InMemoryTokenManager _tokenManager;

        public MembersController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, IMembershipService membershipService,
            IRoleService roleService, ISettingsService settingsService, IEmailService emailService)
            : base(loggingService, unitOfWorkManager, membershipService, roleService, settingsService)
        {
            _emailService = emailService;

            //LoggedOnUser = UserIsAuthenticated ? MembershipService.GetUser(UserName) : null;
            //UsersRole = LoggedOnUser == null ? RoleService.GetRole(AppConstants.GuestRoleName) : LoggedOnUser.Roles.FirstOrDefault();
        }

        [ChildActionOnly]
        public PartialViewResult GetCurrentActiveMembers()
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var viewModel = new ActiveMembersViewModel
                {
                    ActiveMembers = MembershipService.GetActiveMembers()
                };
                return PartialView(viewModel);
            }
        }

        public JsonResult LastActiveCheck()
        {
            if (UserIsAuthenticated)
            {
                var rightNow = DatesUI.getDateTime();
                var usersDate = LoggedOnUser.LastActivityDate ?? DatesUI.getDateTime().AddDays(-1);
                var span = rightNow.Subtract(usersDate);
                var totalMins = span.TotalMinutes;

                if (totalMins > AppConstants.TimeSpanInMinutesToDoCheck)
                {
                    using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
                    {
                        // Update users last activity date so we can show the latest users online
                        LoggedOnUser.LastActivityDate = DatesUI.getDateTime();

                        // Update
                        try
                        {
                            unitOfWork.Commit();
                        }
                        catch (Exception ex)
                        {
                            unitOfWork.Rollback();
                            LoggingService.Error(ex);
                        }
                    }
                }
            }

            // You can return anything to reset the timer.
            return Json(new { Timer = "reset" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetByName(string slug)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var member = MembershipService.GetUserBySlug(slug);
                var loggedonId = UserIsAuthenticated ? LoggedOnUser.Id : Guid.Empty;
                return View(new ViewMemberViewModel { User = member, LoggedOnUserId = loggedonId });
            }
        }

        /// <summary>
        /// Add a new user
        /// </summary>
        /// <returns></returns>
        public ActionResult Register()
        {
            if (SettingsService.GetSettings().SuspendRegistration != true)
            {
                using (UnitOfWorkManager.NewUnitOfWork())
                {
                    var user = MembershipService.CreateEmptyUser();

                    // Populate empty viewmodel
                    var viewModel = new MemberAddViewModel
                    {
                        UserName = user.UserName,
                        Email = user.Email,
                        Password = user.Password,
                        IsApproved = user.IsApproved,
                        Comment = user.Comment,
                        AllRoles = RoleService.AllRoles()
                    };

                    // See if a return url is present or not and add it
                    var returnUrl = Request["ReturnUrl"];
                    if (!string.IsNullOrEmpty(returnUrl))
                    {
                        viewModel.ReturnUrl = returnUrl;
                    }
                    return View(viewModel);
                }
            }
            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Add a new user
        /// </summary>
        /// <param name="userModel"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Register(MemberAddViewModel userModel)
        {
            if (SettingsService.GetSettings().SuspendRegistration != true)
            {
                using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
                {
                    // First see if there is a spam question and if so, the answer matches
                    if (!string.IsNullOrEmpty(SettingsService.GetSettings().SpamQuestion))
                    {
                        // There is a spam question, if answer is wrong return with error
                        if (userModel.SpamAnswer == null || userModel.SpamAnswer.Trim() != SettingsService.GetSettings().SpamAnswer)
                        {
                            // POTENTIAL SPAMMER!
                            ModelState.AddModelError(string.Empty, LocalizationService.GetResourceString("Error.WrongAnswerRegistration"));
                            return View();
                        }
                    }

                    // Secondly see if the email is banned
                    //if (_bannedEmailService.EmailIsBanned(userModel.Email))
                    //{
                    //    ModelState.AddModelError(string.Empty, LocalizationService.GetResourceString("Error.EmailIsBanned"));
                    //    return View();
                    //}

                    var userToSave = new MembershipUser
                    {
                        UserName = userModel.UserName, //_bannedWordService.SanitiseBannedWords(userModel.UserName),
                        Email = userModel.Email,
                        Password = userModel.Password,
                        IsApproved = userModel.IsApproved,
                        Comment = userModel.Comment,
                    };

                    var homeRedirect = false;

                    // Now check settings, see if users need to be manually authorised
                    var manuallyAuthoriseMembers = SettingsService.GetSettings().ManuallyAuthoriseNewMembers;
                    if (manuallyAuthoriseMembers)
                    {
                        userToSave.IsApproved = false;
                    }

                    var createStatus = MembershipService.CreateUser(userToSave);
                    if (createStatus != MembershipCreateStatus.Success)
                    {
                        ModelState.AddModelError(string.Empty, MembershipService.ErrorCodeToString(createStatus));
                    }
                    else
                    {
                        if (!manuallyAuthoriseMembers)
                        {
                            // If not manually authorise then log the user in
                            FormsAuthentication.SetAuthCookie(userToSave.UserName, false);
                            TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                            {
                                Message = LocalizationService.GetResourceString("Members.NowRegistered"),
                                MessageType = GenericMessages.success
                            };
                            homeRedirect = true;
                        }
                        else
                        {
                            ViewBag.Message = new GenericMessageViewModel
                            {
                                Message = LocalizationService.GetResourceString("Members.NowRegisteredNeedApproval"),
                                MessageType = GenericMessages.success
                            };
                        }

                        try
                        {
                            unitOfWork.Commit();
                            if (homeRedirect)
                            {
                                if (Url.IsLocalUrl(userModel.ReturnUrl) && userModel.ReturnUrl.Length > 1 && userModel.ReturnUrl.StartsWith("/")
                                && !userModel.ReturnUrl.StartsWith("//") && !userModel.ReturnUrl.StartsWith("/\\"))
                                {
                                    return Redirect(userModel.ReturnUrl);
                                }
                                return RedirectToAction("Index", "Home", new { area = string.Empty });
                            }
                        }
                        catch (Exception ex)
                        {
                            unitOfWork.Rollback();
                            LoggingService.Error(ex);
                            FormsAuthentication.SignOut();
                            ModelState.AddModelError(string.Empty, LocalizationService.GetResourceString("Errors.GenericMessage"));
                        }
                    }
                    return View();
                }
            }

ResumeBuilder.Web/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@using ResumeBuilder.Web.Application
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="n3o Digital">
    <link href="@Url.Content("~/Content/Admin/Admin.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Admin/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <style type="text/css">
        body
        {
            padding-top: 60px;
            padding-bottom: 0px;
        }
    </style>
    <!--<link href="/css/bootstrap-responsive.css" rel="stylesheet">-->
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script type="text/javascript">
        var app_base = '@Url.Content("~/")';
    </script>
    <script src="@Url.Content("~/Content/scripts/jquery-2.0.3.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/scripts/jquery-ui.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/Admin/bootstrap.min.js")" type="text/javascript"></script>
    @RenderSection("AdminHeader", false)
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <div class="nav-collapse">
                    <ul class="nav">
                        <li><a href="@Url.Content("~/")">Main Site</a></li>
                        <li>@Html.ActionLink("Admin Home", "Index", "Admin")</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        @Html.Partial("_GenericMessage")
        <div class="row">
            @if (User.Identity.IsAuthenticated)
            {
                <div class="span2">
                    <div id="logindisplay">
                        @Html.Partial("_LogOnPartial")
                    </div>
                    <div class="well well-small sidebar-nav">
                        <ul class="nav nav-list">
                            <li class="nav-header">Settings</li>
                            <li><a href="@Url.Action("Index", "Settings", new { area = "Admin" }, null)"><i class='icon-cog'>
                            </i>Configuration </a></li>
                            <li class="nav-header">Membership</li>
                            <li><a href="@Url.Action("Manage", "Account", new { area = "Admin" }, null)"><i class='icon-user'>
                            </i>Manage Users </a></li>
                            <li><a href="@Url.Action("ListAllRoles", "Account", new { area = "Admin" }, null)"><i
                                class="icon-flag"></i>Manage Roles</a> </li>
                            <li><a href="@Url.Action("AddRole", "Account", new { area = "Admin" }, null)"><i
                                class="icon-plus"></i>Add Roles</a> </li>
                            <li class="nav-header">Tools</li>
                            <li><a href="@Url.Action("Index", "Log", new { area = "Admin" })"><i class='icon-exclamation-sign'>
                            </i>Log </a></li>
                            <li><a href="@Url.Action("ScriptDatabase", "Admin", new { area = "Admin" })"><i class='icon-exclamation-sign'>
                            </i>Script Database </a></li>
                        </ul>
                    </div>
                    @*@Html.Partial("_GetCurrentVersion")*@
                </div>
            }
            <div class="span10 mainadminbody">
                @RenderBody()
            </div>
        </div>
        <hr />
    </div>
</body>
</html>

ResumeBuilder.Web/Areas/Admin/Views/Shared/_GenericMessage.cshtml
@using Ecotech.Domain.Constants
@using Ecotech.ViewModels
@{
    var genericMessage = new GenericMessageViewModel();
    if (TempData[AppConstants.MessageViewBagName] != null)
    {
        genericMessage = (GenericMessageViewModel)TempData[AppConstants.MessageViewBagName];
    }
    else if (ViewBag.Message != null)
    {
        genericMessage = (GenericMessageViewModel)ViewBag.Message;
    }
}

<div id="jsquickmessage" style="display:none;"></div>
@if (!string.IsNullOrEmpty(genericMessage.Message))
{
<script type="text/javascript"> $(function () { $('div.alert').delay(1800).fadeOut(); });</script>
<div class="alert alert-block alert-@genericMessage.MessageType.ToString() fade in out">
    <a href="#" data-dismiss="alert" class="close">&times;</a>
    @genericMessage.Message
</div>
}
        

ResumeBuilder.Web/Areas/Admin/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {        
    <text><strong>@User.Identity.Name</strong>
    [@Html.ActionLink("Logoff", "LogOff", "Members", new { area = "" }, null)]</text>
}
else {
    @:[@Html.ActionLink("Logon", "LogOn", "Members", new { area = "" }, null)]
}