ResumeBuilder.Web/Controllers/EmailTemplatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ResumeBuilder.Domain.Interfaces.Services;
using ResumeBuilder.Domain.DomainModel;
using ResumeBuilder.Domain.Interfaces.UnitOfWork;
using ResumeBuilder.Domain.Constants;
using ResumeBuilder.ViewModels;
using ResumeBuilder.Web.Application;
using ResumeBuilder.Utilities;
using System.Net;
using System.Text;

namespace ResumeBuilder.Web.Controllers
{
    public class EmailTemplatesController : BaseController
    {
        private readonly IEmailTemplatesService _emailtemplatesService;

        public EmailTemplatesController(ILoggingService loggingService,
            IUnitOfWorkManager unitOfWorkManager,
            IMembershipService membershipService,
            IRoleService roleService,
            ISettingsService settingsService,
            IEmailTemplatesService emailtemplatesService)
            : base(loggingService, unitOfWorkManager, membershipService, roleService, settingsService)
        {
            _emailtemplatesService = emailtemplatesService;
        }

        [Authorize]
        public ActionResult Index()
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var emailtemplates = _emailtemplatesService.AllEmailTemplates();
                return View(new EmailTemplatesViewModel
                {
                    emailtemplates = emailtemplates
                });
            }
        }

        [Authorize]
        public ActionResult Add()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Add(EmailTemplatesAddModel emailtemplatesAdd)
        {
            using (var newUnitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                EmailTemplates emailtemplates = new EmailTemplates();
                int IEmailTemplatesCount = _emailtemplatesService.GetCount();

                emailtemplates.EmailTemplateId = AppHelpers.GetNewId("ET", IEmailTemplatesCount + 1);
                emailtemplates.EmailTemplateName = emailtemplatesAdd.TemplateName;
                emailtemplates.EmailTemplateSubject = emailtemplatesAdd.TemplateSubject;
                emailtemplates.EmailTemplateBody = emailtemplatesAdd.TemplateBody;
                emailtemplates.LastModified = System.DateTime.Now;
                emailtemplates.IsActive = emailtemplatesAdd.IsActive;

                _emailtemplatesService.Create(emailtemplates);

                try
                {
                    newUnitOfWork.Commit();
                    //Use temp data as itts redirect(when redirection occure it uses this data)
                    TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                    {
                        Message = "Your Email Template is Added Successfully",
                        MessageType = GenericMessages.success,
                    };
                }
                catch (Exception ex)
                {
                    newUnitOfWork.Rollback();
                    LoggingService.Error(ex);
                    //Use temp data as itts redirect(when redirection occure it uses this data)
                    TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                    {
                        Message = string.Format(AppHelpers.GetExceptionMessage(ex)),
                        MessageType = GenericMessages.error,
                    };
                    //throw new Exception("Error while adding Email Template");
                }
                return RedirectToAction("Index");
            }
        }

        [Authorize]
        public ActionResult Details(Guid Id)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                EmailTemplates emailtemplates = _emailtemplatesService.GetEmailById(Id);
                return View(new EmailTemplatesDetails
                {
                    emailtemplates = emailtemplates
                });
            }
        }

        [Authorize]
        public ActionResult Edit(Guid Id)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                EmailTemplates emailtemplates = _emailtemplatesService.GetEmailById(Id);
                return View(new EmailTemplatesEditModel
                {
                    Id = emailtemplates.Id,
                    TemplateId = emailtemplates.EmailTemplateId,
                    TemplateName = emailtemplates.EmailTemplateName,
                    TemplateSubject = emailtemplates.EmailTemplateSubject,
                    TemplateBody = emailtemplates.EmailTemplateBody,
                    LastModified = System.DateTime.Now,
                    IsActive = emailtemplates.IsActive,
                });
            }
        }

        [Authorize]
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(EmailTemplatesEditModel emailtemplatesEdit)
        {
            using (var newUnitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                EmailTemplates emailtemplates = _emailtemplatesService.GetEmailById(emailtemplatesEdit.Id);
                if (emailtemplates != null)
                {
                    emailtemplates.EmailTemplateName = emailtemplatesEdit.TemplateName;
                    emailtemplates.EmailTemplateSubject = emailtemplatesEdit.TemplateSubject;
                    emailtemplates.EmailTemplateBody = emailtemplatesEdit.TemplateBody;
                    emailtemplates.LastModified = System.DateTime.Now;
                    //emailtemplates.IsActive = emailtemplatesEdit.IsActive;

                    try
                    {
                        newUnitOfWork.Commit();
                        TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                        {
                            Message = "Successfully edited Email Template",
                            MessageType = GenericMessages.success
                        };
                    }
                    catch (Exception ex)
                    {
                        newUnitOfWork.Rollback();
                        LoggingService.Error(ex);
                        TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                        {
                            Message = string.Format(AppHelpers.GetExceptionMessage(ex)),
                            MessageType = GenericMessages.error
                        };
                        //throw new Exception("Error Editing Email Template");
                    }
                }
                else
                {
                    LoggingService.Error("Error editing Email Template ID:" + emailtemplates.Id);
                    // Use temp data as its a redirect
                    TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                    {
                        Message = "Error editing Email Template",
                        MessageType = GenericMessages.error
                    };
                }
                return RedirectToAction("Index");
            }
        }

        [Authorize]
        public ActionResult Delete(FormCollection fm)
        {
            using (var NewUnitWork = UnitOfWorkManager.NewUnitOfWork())
            {
                bool fmVal = Convert.ToBoolean(Request.Form["chkSubmit"]);
                foreach (string sName in fm.AllKeys)
                {
                    try
                    {
                        EmailTemplates delemailtemplates = _emailtemplatesService.GetEmailById(AppHelpers.StringToGuid(sName));
                        if (delemailtemplates != null)
                        {
                            delemailtemplates.IsActive = fmVal;
                            delemailtemplates.LastModified = DateUtils.getCurrentDateTime();
                        }
                    }
                    catch
                    {
                        continue;
                    }
                }

                try
                {
                    NewUnitWork.Commit();
                    // Use temp data as its a redirect
                    TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                    {
                        Message = "Email Template status changed...",
                        MessageType = GenericMessages.success
                    };
                }
                catch (Exception ex)
                {
                    NewUnitWork.Rollback();
                    LoggingService.Error(ex);
                    TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                    {
                        Message = string.Format(AppHelpers.GetExceptionMessage(ex)),
                        MessageType = GenericMessages.error
                    };
                }
                return RedirectToAction("Index");
            }
        }
        [Authorize(Roles = AppConstants.RoleNameAdministrator)]
        public ActionResult SetStatus(FormCollection frm)
        {
            using (var NewUnitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                try
                {
                    bool statusVal = Convert.ToBoolean(Request.Form["chkSubmit"].Replace(",", ""));
                    foreach (string id in frm.AllKeys)
                    {
                        try
                        {
                            EmailTemplates changeStatus = _emailtemplatesService.GetEmailById(AppHelpers.StringToGuid(id));
                            if (changeStatus != null)
                            {
                                changeStatus.IsActive = statusVal;
                                changeStatus.LastModified = DateUtils.getCurrentDateTime();
                            }

ResumeBuilder.Web/Views/EmailTemplates/Add.cshtml
@model Ecotech.ViewModels.EmailTemplatesAddModel
@{
    ViewBag.Title = "Email Templates";
    ViewBag.MenuCSSClass = "navEmailTemplates";
}
<article class="blog_post clearfix">
    <!-- START RIGHT POST SIDE -->
    <section class="right_side">
        <div class="block_post">
            <!-- START TITLE -->
            <div class="frmrow">
                <div class="rowleft">
                    <p>Email Templates – ADD</p>
                </div>
                <div class="rowright">
                    <a href="#" class="button grey">Preview</a>
                </div>
            </div>
            <!-- END TITLE -->

            <!-- START TEXT -->
            <div class="clear"></div>
            <!-- END TEXT -->
            <div class="mandatory">* marked fields are mandatory</div>
            @using (Html.BeginForm())
            {
                <fieldset>
                    <div class="frmrow">
                        <div class="frmLabel">
                            @Html.LabelFor(model => model.TemplateName): <span>*</span>
                        </div>
                        <div class="frmElement">
                            @Html.EditorFor(model => model.TemplateName)
                            @Html.ValidationMessageFor(model => model.TemplateName)
                        </div>
                        <div class="clear"></div>
                        <div class="frmLabel">
                            @Html.LabelFor(model => model.TemplateSubject): <span>*</span>
                        </div>
                        <div class="frmElement">
                            @Html.EditorFor(model => model.TemplateSubject)
                            @Html.ValidationMessageFor(model => model.TemplateSubject)
                        </div>
                        <div class="clear"></div>

                        <div class="frmLabel">
                            @Html.LabelFor(model => model.TemplateBody): <span>*</span>
                        </div>
                        <div class="frmElement">
                            @Html.EditorFor(model => model.TemplateBody)
                            @Html.ValidationMessageFor(model => model.TemplateBody)
                        </div>
                        <div class="clear"></div>
                        <div class="frmLabel">
                            @Html.LabelFor(model => model.@IsActive): <span>*</span>
                        </div>
                        <div class="frmElement">
                            @Html.CheckBoxFor(Model => Model.IsActive, new { @checked = "checked" })
                        </div>
                        <div class="clear"></div>
                    </div>

                    <div class="frmElement">
                        <input type="submit" value="Add" class="button grey" onclick="return confirm('Do you want to add new Email template?');" />
                        &nbsp; &nbsp;
                                        <input type="button" class="button grey" title="Cancel" id="btnConverterInfoCancel" value="Cancel" onclick="javascript: history.back();" />
                    </div>
                    <div class="clear"></div>
                </fieldset>
            }
        </div>
    </section>
</article>

ResumeBuilder.Web/Views/EmailTemplates/Details.cshtml
@model Ecotech.ViewModels.EmailTemplatesDetails
@{
    ViewBag.Title = "Email Templates";
    ViewBag.MenuCSSClass = "navEmailTemplates";
    var emailtemp = Model.emailtemplates;
}

<article class="blog_post clearfix">
    <!-- START RIGHT POST SIDE -->
    <section class="right_side">
        <div class="block_post">
            <!-- START TITLE -->
            <div class="frmrow">
                <div class="rowleft">
                    <p>Email Templates – Edit</p>
                </div>
            </div>
            <!-- END TITLE -->

            <!-- START TEXT -->
            <div class="clear"></div>
            <!-- END TEXT -->
            @using (Html.BeginForm())
            {
                <fieldset>
                    <div class="frmrow">
                        <div class="frmLabel">
                            <label>
                                Template ID:</label>
                        </div>
                        <div class="frmElement">
                            <label>
                                @emailtemp.EmailTemplateId</label>
                        </div>
                        <div class="clear"></div>
                        <div class="frmLabel">
                            <label>
                                Template Name:</label>
                        </div>
                        <div class="frmElement">
                            <label>
                                @emailtemp.EmailTemplateName</label>
                        </div>
                        <div class="clear"></div>
                        <div class="frmLabel">
                            <label>
                                Template Subject :</label>
                        </div>
                        <div class="frmElement">
                            <label>
                                @emailtemp.EmailTemplateSubject</label>
                        </div>
                        <div class="clear"></div>

                        <div class="frmLabel">
                            <label>
                                Template Body:</label>
                        </div>
                        <div class="frmElement">
                            <label>
                                @Html.Raw(Html.Encode(emailtemp.EmailTemplateBody).Replace("\n", "<br />"))
                                <br />
                            </label>
                        </div>
                        <div class="clear"></div>
                        <div class="frmLabel">
                            Status:
                        </div>
                        <div class="frmElement">
                            @if (@emailtemp.IsActive == true)
                            {
                                <label style="color: #4fa800">
                                    Active</label>
                            }
                            else
                            {
                                <label style="color: #ff0000">
                                    Inactive</label>
                            }
                        </div>
                        <div class="clear"></div>
                    </div>

                    <div class="frmElement">
                        <a class="button grey" id="btnConverterInfoCancel" onclick="javascript: history.back();">Back</a>
                        <a  href="@Url.Action("Edit", new { Id = emailtemp.Id })"class="button grey" style="display:none;">Edit</a>
                    </div>
                    <div class="clear"></div>
                </fieldset>
            }
        </div>
    </section>
</article>

ResumeBuilder.Web/Views/EmailTemplates/Edit.cshtml
@model Ecotech.ViewModels.EmailTemplatesEditModel
@{
    ViewBag.Title = "Email Templates";
    ViewBag.MenuCSSClass = "navEmailTemplates";
}
<article class="blog_post clearfix">
    <!-- START RIGHT POST SIDE -->
    <section class="right_side">
        <div class="block_post">
            <!-- START TITLE -->
            <div class="frmrow">
                <div class="rowleft">
                    <p>Email Templates – Edit</p>
                </div>
                <div class="rowright">
                    <a href="#" class="button grey">Preview</a>
                </div>
            </div>
            <!-- END TITLE -->

            <!-- START TEXT -->
            <div class="clear"></div>
            <!-- END TEXT -->
            <div class="mandatory">* marked fields are mandatory</div>
            @using (Html.BeginForm())
            {
                <fieldset>
                    <div class="frmrow">
                        <div class="frmLabel">
                            @Html.LabelFor(model => model.TemplateId): <span>*</span>
                        </div>
                        <div class="frmElement">
                            @Html.HiddenFor(model => model.Id)
                            <label>@Model.TemplateId</label>
                        </div>
                        <div class="clear"></div>
                        <div class="frmLabel">
                            @Html.LabelFor(model => model.TemplateName): <span>*</span>
                        </div>
                        <div class="frmElement">
                            @Html.EditorFor(model => model.TemplateName)
                            @Html.ValidationMessageFor(model => model.TemplateName)
                        </div>
                        <div class="clear"></div>
                        <div class="frmLabel">
                            @Html.LabelFor(model => model.TemplateSubject): <span>*</span>
                        </div>
                        <div class="frmElement">
                            @Html.EditorFor(model => model.TemplateSubject)
                            @Html.ValidationMessageFor(model => model.TemplateSubject)
                        </div>
                        <div class="clear"></div>

                        <div class="frmLabel">
                            @Html.LabelFor(model => model.TemplateBody): <span>*</span>
                        </div>
                        <div class="frmElement">
                            @Html.EditorFor(model => model.TemplateBody)
                            @Html.ValidationMessageFor(model => model.TemplateBody)
                        </div>
                        <div class="clear"></div>
                        <div class="frmLabel">
                            @Html.LabelFor(model => model.@IsActive): <span>*</span>
                        </div>
                        <div class="frmElement">
                            @if (Model.IsActive == true)
                            {
                                <label style="color: #4fa800">
                                    Active</label>
                            }
                            else if (Model.IsActive == false)
                            {
                                <label style="color: #ff0000">
                                    Inactive</label>
                            }
                        </div>
                        <div class="clear"></div>
                    </div>

                    <div class="frmElement">
                        <input type="submit" value="Save" class="button grey" onclick="return confirm('Do you want to add new Email template?');" />
                        &nbsp; &nbsp;
                                        <input type="button" class="button grey" title="Cancel" id="btnConverterInfoCancel" value="Cancel" onclick="javascript: history.back();" />
                    </div>
                    <div class="clear"></div>
                </fieldset>
            }
        </div>
    </section>
</article>

ResumeBuilder.Web/Views/EmailTemplates/Index.cshtml
@model Ecotech.ViewModels.EmailTemplatesViewModel
@{
    ViewBag.Title = "Email Templates";
    ViewBag.MenuCSSClass = "navEmailTemplates";
}

@section HeaderSection{
    <link href="@Url.Content("~/Content/css/responsive-tables.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/css/libs/sprite.tables.css")" rel="stylesheet" />
}

<article class="blog_post clearfix">
    <!-- START RIGHT POST SIDE -->
    <section class="right_side">
        <div class="block_post">

            <!-- START TITLE -->
            <div class="frmrow">
                <div class="rowleft">
                    <p>Manage Email Templates</p>
                </div>
            </div>
            <!-- END TITLE -->
            <div class="clear"></div>
            <!-- START TEXT -->
            @using (Html.BeginForm("Delete", "EmailTemplates", FormMethod.Post, new { @Id = "DataGrid" }))
            {
            
                <table id="table-example" class="table responsive">
                    <thead>
                        <tr>
                            <th style="text-align: center">
                                <input type="checkbox" name="Test" onclick="SetAllCheckBoxes(this)" />
                                <input id="chkSubmit" name="chkSubmit" type="hidden" />
                            </th>
                            <th>Template ID</th>
                            <th>Template Name</th>
                            <th>Template Subject</th>
                            <th>Modified On</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var emailtemplates in Model.emailtemplates)
                        {
                            <tr class="gradeX">
                                <td style="width: 8%; text-align: center">
                                    <input type="checkbox"  name="@emailtemplates.Id" />
                                </td>
                                <td>
                                    @emailtemplates.EmailTemplateId
                                </td>
                                <td>
                                    @emailtemplates.EmailTemplateName
                                </td>
                                <td>
                                    @emailtemplates.EmailTemplateSubject
                                </td>
                                <td>
                                    @SKF_LCO_System.Utilities.DateUtils.FormatDateTime(emailtemplates.LastModified.ToString(), AppConstants.DefaultDateFormat)
                                </td>
                                @if (emailtemplates.IsActive == true)
                                {
                                    <td style="color: #4fa800">Active
                                    </td>
                                }
                                else
                                {
                                    <td style="color: #ff0000">Inactive
                                    </td>
                                }
                                <td style="width: 10%">
                                    @*  <a href="@Url.Action("Edit", new { Id = emailtemplates.Id })" >Edit</a> &nbsp | &nbsp *@
                                    <a href="@Url.Action("Details", new { Id = emailtemplates.Id })">View</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            <div class="clear"></div>
            @if (@Model.emailtemplates.Count != 0)
            {
                <div class="row1">
                    <a class="button grey" onclick="statusChange('Active','EmailTemplates','Email Templates')">Active</a>
                    <a class="button grey" onclick="statusChange('Inactive','EmailTemplates','Email Templates');">Inactive</a>
                    <a href="#" class="button grey" onclick="javascript:fnDelete();" style="display: none">Delete</a>
                </div>
            }
            <!-- END TEXT -->

        </div>
    </section>
</article>
@section FooterSection{
    <script src="@Url.Content("~/Content/js/lib/jquery.dataTables.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/js/responsive-tables.js")" type="text/javascript"></script>
    <script type="text/javascript">
        $(window).load(function () {
            $("#table-example").dataTable({
                "aoColumnDefs": [
              { 'bSortable': false, 'aTargets': [0, -1] }
                ]
            }).wrap('<div class="tablecont" />');
            $(window).resize();
        });
        disableCheckBox('@Model.emailtemplates.Count');
    </script>
}